# Generated by adevtool; do not edit
# For more info, see https://github.com/kdrag0n/adevtool

# Inherit AOSP product
$(call inherit-product, device/google/coral/aosp_flame.mk)

# Match stock product info
PRODUCT_NAME := flame
PRODUCT_MODEL := Pixel 4
PRODUCT_BRAND := google
PRODUCT_MANUFACTURER := Google
