# Generated by adevtool; do not edit
# For more info, see https://github.com/kdrag0n/adevtool

# Inherit AOSP product
$(call inherit-product, device/google/redfin/aosp_redfin.mk)

# Match stock product info
PRODUCT_NAME := redfin
PRODUCT_MODEL := Pixel 5
PRODUCT_BRAND := google
PRODUCT_MANUFACTURER := Google
