# Generated by adevtool; do not edit
# For more info, see https://github.com/kdrag0n/adevtool

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),raven)

$(call add-radio-file,firmware/bootloader.img)
$(call add-radio-file,firmware/radio.img)

include $(CLEAR_VARS)
LOCAL_MODULE := device_symlinks
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := google_devices
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR_ETC)
LOCAL_MODULE_STEM := .device_symlinks
LOCAL_SRC_FILES := Android.mk
LOCAL_POST_INSTALL_CMD := \
    mkdir -p $(PRODUCT_OUT)/product/priv-app/DMService/lib/arm; \
    mkdir -p $(PRODUCT_OUT)/system_ext/priv-app/HbmSVManager/lib/arm64; \
    ln -sf /product/lib/libdmengine.so $(PRODUCT_OUT)/product/priv-app/DMService/lib/arm/libdmengine.so; \
    ln -sf /product/lib/libdmjavaplugin.so $(PRODUCT_OUT)/product/priv-app/DMService/lib/arm/libdmjavaplugin.so; \
    ln -sf /system_ext/lib64/libhbmsvmanager_jni.so $(PRODUCT_OUT)/system_ext/priv-app/HbmSVManager/lib/arm64/libhbmsvmanager_jni.so; \
    rm -f $(TARGET_OUT_VENDOR_ETC)/.device_symlinks
include $(BUILD_PREBUILT)

endif
