# Generated by adevtool; do not edit
# For more info, see https://github.com/kdrag0n/adevtool

# Inherit AOSP product
$(call inherit-product, device/google/bramble/aosp_bramble.mk)

# Match stock product info
PRODUCT_NAME := bramble
PRODUCT_MODEL := Pixel 4a (5G)
PRODUCT_BRAND := google
PRODUCT_MANUFACTURER := Google
